#!/usr/bin/env python3

import json
from pprint import pprint

with open('mega blastoise.json') as f:
    data = json.load(f)
f.close()

pprint(data)
print("Name: " + data["name"])
print("Speed: " + str(data["speed"]))
print("Defense: " + str(dat["defense"]))
for move in data["move"]:
    print(move["name"
